nelmio_api_doc:
    documentation:
        info:
            title: API
            version: '1.0'
        openapi: '3.0.0'
    areas:
        default:
            path_patterns:
                - ^/{aaaa}/ggggg
                - ^/{aaaa}/prprprp
                - ^/pepepepe/
                - ^/profile
                - ^/uuuuuu/mmmmm
                - ^/prprprp/
                - ^/nnnn/
                - ^/tttt/prprprp/{prprprpId}/vvvv
