services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    App\Controller\:
        resource: '../src/App/Controller'
        tags: ['controller.service_arguments']
